#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MoviesDB")]
public partial class MoviesDBDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertDevLog(DevLog instance);
  partial void UpdateDevLog(DevLog instance);
  partial void DeleteDevLog(DevLog instance);
  partial void InsertRtMovy(RtMovy instance);
  partial void UpdateRtMovy(RtMovy instance);
  partial void DeleteRtMovy(RtMovy instance);
  partial void InsertNetflixMovy(NetflixMovy instance);
  partial void UpdateNetflixMovy(NetflixMovy instance);
  partial void DeleteNetflixMovy(NetflixMovy instance);
  #endregion
	
	public MoviesDBDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["MoviesDBConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public MoviesDBDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public MoviesDBDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public MoviesDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public MoviesDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<DevLog> DevLogs
	{
		get
		{
			return this.GetTable<DevLog>();
		}
	}
	
	public System.Data.Linq.Table<RtMovy> RtMovies
	{
		get
		{
			return this.GetTable<RtMovy>();
		}
	}
	
	public System.Data.Linq.Table<NetflixMovy> NetflixMovies
	{
		get
		{
			return this.GetTable<NetflixMovy>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DevLog")]
public partial class DevLog : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _LogID;
	
	private string _Message;
	
	private System.Nullable<System.DateTime> _Date;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLogIDChanging(int value);
    partial void OnLogIDChanged();
    partial void OnMessageChanging(string value);
    partial void OnMessageChanged();
    partial void OnDateChanging(System.Nullable<System.DateTime> value);
    partial void OnDateChanged();
    #endregion
	
	public DevLog()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int LogID
	{
		get
		{
			return this._LogID;
		}
		set
		{
			if ((this._LogID != value))
			{
				this.OnLogIDChanging(value);
				this.SendPropertyChanging();
				this._LogID = value;
				this.SendPropertyChanged("LogID");
				this.OnLogIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Message", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
	public string Message
	{
		get
		{
			return this._Message;
		}
		set
		{
			if ((this._Message != value))
			{
				this.OnMessageChanging(value);
				this.SendPropertyChanging();
				this._Message = value;
				this.SendPropertyChanged("Message");
				this.OnMessageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime")]
	public System.Nullable<System.DateTime> Date
	{
		get
		{
			return this._Date;
		}
		set
		{
			if ((this._Date != value))
			{
				this.OnDateChanging(value);
				this.SendPropertyChanging();
				this._Date = value;
				this.SendPropertyChanged("Date");
				this.OnDateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RtMovies")]
public partial class RtMovy : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _RtMovieID;
	
	private string _AudienceScore;
	
	private string _CriticsScore;
	
	private string _AudienceRating;
	
	private string _CriticsRating;
	
	private string _WebsiteLink;
	
	private int _MovieID;
	
	private EntityRef<NetflixMovy> _NetflixMovy;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRtMovieIDChanging(int value);
    partial void OnRtMovieIDChanged();
    partial void OnAudienceScoreChanging(string value);
    partial void OnAudienceScoreChanged();
    partial void OnCriticsScoreChanging(string value);
    partial void OnCriticsScoreChanged();
    partial void OnAudienceRatingChanging(string value);
    partial void OnAudienceRatingChanged();
    partial void OnCriticsRatingChanging(string value);
    partial void OnCriticsRatingChanged();
    partial void OnWebsiteLinkChanging(string value);
    partial void OnWebsiteLinkChanged();
    partial void OnMovieIDChanging(int value);
    partial void OnMovieIDChanged();
    #endregion
	
	public RtMovy()
	{
		this._NetflixMovy = default(EntityRef<NetflixMovy>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RtMovieID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int RtMovieID
	{
		get
		{
			return this._RtMovieID;
		}
		set
		{
			if ((this._RtMovieID != value))
			{
				this.OnRtMovieIDChanging(value);
				this.SendPropertyChanging();
				this._RtMovieID = value;
				this.SendPropertyChanged("RtMovieID");
				this.OnRtMovieIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AudienceScore", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string AudienceScore
	{
		get
		{
			return this._AudienceScore;
		}
		set
		{
			if ((this._AudienceScore != value))
			{
				this.OnAudienceScoreChanging(value);
				this.SendPropertyChanging();
				this._AudienceScore = value;
				this.SendPropertyChanged("AudienceScore");
				this.OnAudienceScoreChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CriticsScore", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string CriticsScore
	{
		get
		{
			return this._CriticsScore;
		}
		set
		{
			if ((this._CriticsScore != value))
			{
				this.OnCriticsScoreChanging(value);
				this.SendPropertyChanging();
				this._CriticsScore = value;
				this.SendPropertyChanged("CriticsScore");
				this.OnCriticsScoreChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AudienceRating", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string AudienceRating
	{
		get
		{
			return this._AudienceRating;
		}
		set
		{
			if ((this._AudienceRating != value))
			{
				this.OnAudienceRatingChanging(value);
				this.SendPropertyChanging();
				this._AudienceRating = value;
				this.SendPropertyChanged("AudienceRating");
				this.OnAudienceRatingChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CriticsRating", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string CriticsRating
	{
		get
		{
			return this._CriticsRating;
		}
		set
		{
			if ((this._CriticsRating != value))
			{
				this.OnCriticsRatingChanging(value);
				this.SendPropertyChanging();
				this._CriticsRating = value;
				this.SendPropertyChanged("CriticsRating");
				this.OnCriticsRatingChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WebsiteLink", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
	public string WebsiteLink
	{
		get
		{
			return this._WebsiteLink;
		}
		set
		{
			if ((this._WebsiteLink != value))
			{
				this.OnWebsiteLinkChanging(value);
				this.SendPropertyChanging();
				this._WebsiteLink = value;
				this.SendPropertyChanged("WebsiteLink");
				this.OnWebsiteLinkChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MovieID", DbType="Int NOT NULL")]
	public int MovieID
	{
		get
		{
			return this._MovieID;
		}
		set
		{
			if ((this._MovieID != value))
			{
				if (this._NetflixMovy.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnMovieIDChanging(value);
				this.SendPropertyChanging();
				this._MovieID = value;
				this.SendPropertyChanged("MovieID");
				this.OnMovieIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NetflixMovy_RtMovy", Storage="_NetflixMovy", ThisKey="MovieID", OtherKey="MovieID", IsForeignKey=true)]
	public NetflixMovy NetflixMovy
	{
		get
		{
			return this._NetflixMovy.Entity;
		}
		set
		{
			NetflixMovy previousValue = this._NetflixMovy.Entity;
			if (((previousValue != value) 
						|| (this._NetflixMovy.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._NetflixMovy.Entity = null;
					previousValue.RtMovies.Remove(this);
				}
				this._NetflixMovy.Entity = value;
				if ((value != null))
				{
					value.RtMovies.Add(this);
					this._MovieID = value.MovieID;
				}
				else
				{
					this._MovieID = default(int);
				}
				this.SendPropertyChanged("NetflixMovy");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NetflixMovies")]
public partial class NetflixMovy : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _MovieID;
	
	private string _NetflixID;
	
	private int _ReleaseYear;
	
	private string _Rating;
	
	private string _Synopsis;
	
	private string _ShortSynopsis;
	
	private double _AverageRating;
	
	private string _LargeUrl;
	
	private int _Runtime;
	
	private System.DateTime _ExpiresDate;
	
	private string _Title;
	
	private string _Type;
	
	private System.Nullable<int> _ApiID;
	
	private EntitySet<RtMovy> _RtMovies;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMovieIDChanging(int value);
    partial void OnMovieIDChanged();
    partial void OnNetflixIDChanging(string value);
    partial void OnNetflixIDChanged();
    partial void OnReleaseYearChanging(int value);
    partial void OnReleaseYearChanged();
    partial void OnRatingChanging(string value);
    partial void OnRatingChanged();
    partial void OnSynopsisChanging(string value);
    partial void OnSynopsisChanged();
    partial void OnShortSynopsisChanging(string value);
    partial void OnShortSynopsisChanged();
    partial void OnAverageRatingChanging(double value);
    partial void OnAverageRatingChanged();
    partial void OnLargeUrlChanging(string value);
    partial void OnLargeUrlChanged();
    partial void OnRuntimeChanging(int value);
    partial void OnRuntimeChanged();
    partial void OnExpiresDateChanging(System.DateTime value);
    partial void OnExpiresDateChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnTypeChanging(string value);
    partial void OnTypeChanged();
    partial void OnApiIdChanging(System.Nullable<int> value);
    partial void OnApiIdChanged();
    #endregion
	
	public NetflixMovy()
	{
		this._RtMovies = new EntitySet<RtMovy>(new Action<RtMovy>(this.attach_RtMovies), new Action<RtMovy>(this.detach_RtMovies));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MovieID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int MovieID
	{
		get
		{
			return this._MovieID;
		}
		set
		{
			if ((this._MovieID != value))
			{
				this.OnMovieIDChanging(value);
				this.SendPropertyChanging();
				this._MovieID = value;
				this.SendPropertyChanged("MovieID");
				this.OnMovieIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NetflixID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string NetflixID
	{
		get
		{
			return this._NetflixID;
		}
		set
		{
			if ((this._NetflixID != value))
			{
				this.OnNetflixIDChanging(value);
				this.SendPropertyChanging();
				this._NetflixID = value;
				this.SendPropertyChanged("NetflixID");
				this.OnNetflixIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReleaseYear", DbType="Int NOT NULL")]
	public int ReleaseYear
	{
		get
		{
			return this._ReleaseYear;
		}
		set
		{
			if ((this._ReleaseYear != value))
			{
				this.OnReleaseYearChanging(value);
				this.SendPropertyChanging();
				this._ReleaseYear = value;
				this.SendPropertyChanged("ReleaseYear");
				this.OnReleaseYearChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rating", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Rating
	{
		get
		{
			return this._Rating;
		}
		set
		{
			if ((this._Rating != value))
			{
				this.OnRatingChanging(value);
				this.SendPropertyChanging();
				this._Rating = value;
				this.SendPropertyChanged("Rating");
				this.OnRatingChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Synopsis", DbType="VarChar(1000) NOT NULL", CanBeNull=false)]
	public string Synopsis
	{
		get
		{
			return this._Synopsis;
		}
		set
		{
			if ((this._Synopsis != value))
			{
				this.OnSynopsisChanging(value);
				this.SendPropertyChanging();
				this._Synopsis = value;
				this.SendPropertyChanged("Synopsis");
				this.OnSynopsisChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShortSynopsis", DbType="VarChar(1000) NOT NULL", CanBeNull=false)]
	public string ShortSynopsis
	{
		get
		{
			return this._ShortSynopsis;
		}
		set
		{
			if ((this._ShortSynopsis != value))
			{
				this.OnShortSynopsisChanging(value);
				this.SendPropertyChanging();
				this._ShortSynopsis = value;
				this.SendPropertyChanged("ShortSynopsis");
				this.OnShortSynopsisChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AverageRating", DbType="Float NOT NULL")]
	public double AverageRating
	{
		get
		{
			return this._AverageRating;
		}
		set
		{
			if ((this._AverageRating != value))
			{
				this.OnAverageRatingChanging(value);
				this.SendPropertyChanging();
				this._AverageRating = value;
				this.SendPropertyChanged("AverageRating");
				this.OnAverageRatingChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LargeUrl", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
	public string LargeUrl
	{
		get
		{
			return this._LargeUrl;
		}
		set
		{
			if ((this._LargeUrl != value))
			{
				this.OnLargeUrlChanging(value);
				this.SendPropertyChanging();
				this._LargeUrl = value;
				this.SendPropertyChanged("LargeUrl");
				this.OnLargeUrlChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Runtime", DbType="Int NOT NULL")]
	public int Runtime
	{
		get
		{
			return this._Runtime;
		}
		set
		{
			if ((this._Runtime != value))
			{
				this.OnRuntimeChanging(value);
				this.SendPropertyChanging();
				this._Runtime = value;
				this.SendPropertyChanged("Runtime");
				this.OnRuntimeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpiresDate", DbType="DateTime NOT NULL")]
	public System.DateTime ExpiresDate
	{
		get
		{
			return this._ExpiresDate;
		}
		set
		{
			if ((this._ExpiresDate != value))
			{
				this.OnExpiresDateChanging(value);
				this.SendPropertyChanging();
				this._ExpiresDate = value;
				this.SendPropertyChanged("ExpiresDate");
				this.OnExpiresDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
	public string Title
	{
		get
		{
			return this._Title;
		}
		set
		{
			if ((this._Title != value))
			{
				this.OnTitleChanging(value);
				this.SendPropertyChanging();
				this._Title = value;
				this.SendPropertyChanged("Title");
				this.OnTitleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="VarChar(50)")]
	public string Type
	{
		get
		{
			return this._Type;
		}
		set
		{
			if ((this._Type != value))
			{
				this.OnTypeChanging(value);
				this.SendPropertyChanging();
				this._Type = value;
				this.SendPropertyChanged("Type");
				this.OnTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ApiID", Storage="_ApiID", DbType="Int")]
	public System.Nullable<int> ApiId
	{
		get
		{
			return this._ApiID;
		}
		set
		{
			if ((this._ApiID != value))
			{
				this.OnApiIdChanging(value);
				this.SendPropertyChanging();
				this._ApiID = value;
				this.SendPropertyChanged("ApiId");
				this.OnApiIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NetflixMovy_RtMovy", Storage="_RtMovies", ThisKey="MovieID", OtherKey="MovieID")]
	public EntitySet<RtMovy> RtMovies
	{
		get
		{
			return this._RtMovies;
		}
		set
		{
			this._RtMovies.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_RtMovies(RtMovy entity)
	{
		this.SendPropertyChanging();
		entity.NetflixMovy = this;
	}
	
	private void detach_RtMovies(RtMovy entity)
	{
		this.SendPropertyChanging();
		entity.NetflixMovy = null;
	}
}
#pragma warning restore 1591
